(function(){'use strict';
const KEY='lexora-v6-local';
const DAILY=[
['Pragmatic','dealing with problems in a practical, realistic way','A pragmatic approach can reduce unnecessary costs.'],['Mitigate','to make something less severe, harmful, or difficult','The company introduced controls to mitigate financial risk.'],['Viable','capable of working successfully or being sustained','We need a financially viable business model.'],['Leverage','to use an advantage, resource, or asset effectively','The firm leveraged technology to improve productivity.'],['Articulate','to express an idea clearly and effectively','She articulated the proposal with confidence.'],['Scrutinize','to examine something very carefully','Investors scrutinized the quarterly results.'],['Consolidate','to combine things into a stronger or more effective whole','The group consolidated its regional operations.'],['Substantiate','to support a claim with evidence','The report must substantiate the proposed benefits.'],['Resilient','able to recover or adapt after difficulty','The business remained resilient during the downturn.'],['Ambiguous','open to more than one interpretation; unclear','The contract contained an ambiguous clause.'],['Nuanced','showing subtle differences or distinctions','The manager gave a nuanced assessment of the market.'],['Proactive','acting in advance rather than reacting later','A proactive risk policy can prevent losses.'],['Feasible','possible and practical to achieve','The team evaluated whether the expansion was feasible.'],['Coherent','logical, consistent, and easy to understand','Her presentation gave a coherent view of the strategy.'],['Substantial','large in amount or important in effect','The project requires substantial investment.'],['Discrepancy','a difference between things that should agree','The auditor noticed a discrepancy in the records.'],['Comprehensive','including all or nearly all relevant aspects','We prepared a comprehensive market analysis.'],['Foster','to encourage the development of something','The program aims to foster innovation.'],['Allocate','to distribute resources for a particular purpose','Management allocated more funds to research.'],['Benchmark','a standard used to compare performance','The company benchmarked its costs against competitors.']];
let state=load(), current=null, fcIndex=0, fcFlipped=false, cloud=null, user=null, authMode='signin', syncTimer=null;
const hasCloud=()=>!!(window.supabase&&window.LEXORA_SUPABASE_URL&&window.LEXORA_SUPABASE_PUBLISHABLE_KEY);
if(hasCloud()) cloud=window.supabase.createClient(window.LEXORA_SUPABASE_URL,window.LEXORA_SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{words:[],history:{},theme:'light'}}catch(e){return{words:[],history:{},theme:'light'}}}
function localSave(){localStorage.setItem(KEY,JSON.stringify(state))}
function today(){return new Date().toISOString().slice(0,10)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(t){const x=document.getElementById('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2400)}
function applyTheme(){const dark=state.theme==='dark';document.documentElement.classList.toggle('dark',dark);document.documentElement.style.colorScheme=dark?'dark':'light';const b=document.getElementById('theme');if(b){b.textContent=dark?'☀':'☾';b.title=dark?'Light mode':'Dark mode'}}
function speak(text){if(!text)return;if(!('speechSynthesis' in window)){toast('Speech is not supported by this browser.');return}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.82;const voices=speechSynthesis.getVoices();const v=voices.find(x=>/^en(-|_)/i.test(x.lang));if(v)u.voice=v;speechSynthesis.speak(u)}
if('speechSynthesis' in window) speechSynthesis.onvoiceschanged=()=>{};
window.lexSpeak=speak;
function page(name){if(!document.getElementById('page-'+name))name='search';document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById('page-'+name).classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===name));location.hash=name;if(name==='words')renderWords();if(name==='activity')renderCalendar();if(name==='flashcards')setupFC()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>page(b.dataset.page));

document.getElementById('theme').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';applyTheme();localSave();};

document.getElementById('searchSpeak').onclick=()=>speak(document.getElementById('wordInput').value.trim());
async function dictionary(word){const url='https://api.dictionaryapi.dev/api/v2/entries/en/'+encodeURIComponent(word);const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('not found');return r.json()}
function renderResult(data,word){let phon=data[0]?.phonetic||'',phonAudio='',meanings=[];data.forEach(entry=>{if(!phon&&entry.phonetic)phon=entry.phonetic;(entry.phonetics||[]).forEach(p=>{if(!phonAudio&&p.audio)phonAudio=p.audio});(entry.meanings||[]).forEach(m=>meanings.push({pos:m.partOfSpeech||'',defs:m.definitions||[]}))});const grouped=[],seen=new Set();meanings.forEach(m=>m.defs.forEach(d=>{const k=(m.pos+'|'+d.definition).toLowerCase();if(!seen.has(k)){seen.add(k);grouped.push({pos:m.pos,definition:d.definition,example:d.example})}}));current={word,phonetic:phon,meanings:grouped,synonyms:[...new Set(data.flatMap(e=>e.meanings||[]).flatMap(m=>m.synonyms||[]))],antonyms:[...new Set(data.flatMap(e=>e.meanings||[]).flatMap(m=>m.antonyms||[]))],audio:phonAudio,source:'user'};showResult(current)}
function showResult(x){const r=document.getElementById('result');r.classList.remove('hidden');let html='<div class="result-head"><div><h2>'+esc(x.word)+'</h2><div class="phonetic">'+esc(x.phonetic||'Pronunciation available below')+'</div></div><button class="audio" id="resultAudio">🔊</button></div>';x.meanings.forEach((m,i)=>{html+='<div class="meaning"><h3>'+esc(m.pos||'Meaning '+(i+1))+'</h3><p><span class="label">'+(i+1)+'.</span> '+esc(m.definition)+'</p>'+(m.example?'<p><em>Example: '+esc(m.example)+'</em></p>':'')+'</div>'});if(x.synonyms?.length)html+='<div class="meaning"><h3>Synonyms</h3><div class="chips">'+x.synonyms.slice(0,20).map(s=>'<span class="chip">'+esc(s)+'</span>').join('')+'</div></div>';if(x.antonyms?.length)html+='<div class="meaning"><h3>Antonyms</h3><div class="chips">'+x.antonyms.slice(0,20).map(s=>'<span class="chip">'+esc(s)+'</span>').join('')+'</div></div>';html+='<button class="primary save" id="saveResult">+ Add to My Words</button>';r.innerHTML=html;document.getElementById('resultAudio').onclick=()=>{if(x.audio){const a=new Audio(x.audio);a.play().catch(()=>speak(x.word))}else speak(x.word)};document.getElementById('saveResult').onclick=()=>saveWord(x)}
async function searchWord(word){word=word.trim().toLowerCase();if(!word)return;const r=document.getElementById('result');r.classList.remove('hidden');r.innerHTML='<p>Searching…</p>';try{const data=await dictionary(word);renderResult(data,word)}catch(e){r.innerHTML='<h2>Could not find “'+esc(word)+'”</h2><p>Check the spelling or try another English word.</p><button class="audio" id="fallbackAudio">🔊 Pronounce</button>';document.getElementById('fallbackAudio').onclick=()=>speak(word)}}
document.getElementById('searchForm').onsubmit=e=>{e.preventDefault();searchWord(document.getElementById('wordInput').value)};
function dailyWords(){const start=new Date('2026-01-01T00:00:00');const diff=Math.floor((new Date(new Date().toDateString())-start)/86400000);const offset=((diff%DAILY.length)+DAILY.length)%DAILY.length;return Array.from({length:10},(_,i)=>DAILY[(offset+i)%DAILY.length])}
function renderDaily(){document.getElementById('dailyGrid').innerHTML=dailyWords().map(w=>'<article class="daily-card"><button onclick="window.lexSpeak('+JSON.stringify(w[0])+')">🔊</button><h3>'+esc(w[0])+'</h3><p>'+esc(w[1])+'</p><p><em>'+esc(w[2])+'</em></p><button class="secondary daily-save" data-word="'+esc(w[0])+'">Add</button></article>').join('');document.querySelectorAll('.daily-save').forEach(b=>b.onclick=()=>{const w=dailyWords().find(x=>x[0].toLowerCase()===b.dataset.word.toLowerCase());if(w)saveWord({word:w[0].toLowerCase(),phonetic:'',meanings:[{pos:'',definition:w[1],example:w[2]}],synonyms:[],antonyms:[],audio:'',source:'daily'})})}
document.getElementById('refreshDaily').onclick=renderDaily;
function addLocalWord(w){const existing=state.words.find(y=>y.word_key===w.word.toLowerCase());const record={...w,word_key:w.word.toLowerCase(),id:existing?.id||crypto.randomUUID?.()||Date.now().toString(),addedAt:existing?.addedAt||new Date().toISOString(),reviews:existing?.reviews||0};state.words=[record,...state.words.filter(y=>y.word_key!==record.word_key)];const d=today();state.history[d]??={added:[],reviewed:[]};if(!state.history[d].added.includes(record.word))state.history[d].added.push(record.word);localSave();return record}
async function syncWordToCloud(w){if(!cloud||!user)return;const payload={phonetic:w.phonetic||'',meanings:w.meanings||[],synonyms:w.synonyms||[],antonyms:w.antonyms||[],audio:w.audio||''};const {error}=await cloud.from('words').upsert({user_id:user.id,word_key:w.word.toLowerCase(),word:w.word,payload,source:w.source||'user',added_at:w.addedAt||new Date().toISOString(),reviews:w.reviews||0},{onConflict:'user_id,word_key'});if(error)throw error}
async function saveWord(x){const record=addLocalWord(x);if(user){try{await syncWordToCloud(record);await syncActivity();toast('Saved and synced to your account')}catch(e){toast('Saved locally; cloud sync failed')}}else toast('Saved locally. Sign in to sync across devices.');renderWords()}
async function syncActivity(){if(!cloud||!user)return;const d=today(),h=state.history[d]||{added:[],reviewed:[]};const {error}=await cloud.from('activity').upsert({user_id:user.id,activity_date:d,added_count:h.added.length,reviewed_count:h.reviewed.length,added_words:h.added,reviewed_words:h.reviewed},{onConflict:'user_id,activity_date'});if(error)throw error}
async function migrateLocalToCloud(){if(!cloud||!user||!state.words.length)return;for(const w of state.words){try{await syncWordToCloud(w)}catch(e){}}try{await syncActivity()}catch(e){}}
async function loadCloudData(){if(!cloud||!user)return;await migrateLocalToCloud();const [wr,ar]=await Promise.all([cloud.from('words').select('*').order('added_at',{ascending:false}),cloud.from('activity').select('*')]);if(wr.error)throw wr.error;if(ar.error)throw ar.error;state.words=(wr.data||[]).map(r=>({id:r.id,word:r.word,word_key:r.word_key,phonetic:r.payload?.phonetic||'',meanings:r.payload?.meanings||[],synonyms:r.payload?.synonyms||[],antonyms:r.payload?.antonyms||[],audio:r.payload?.audio||'',source:r.source,addedAt:r.added_at,reviews:r.reviews||0}));state.history={};(ar.data||[]).forEach(r=>state.history[r.activity_date]={added:r.added_words||[],reviewed:r.reviewed_words||[]});localSave();renderWords();renderCalendar();setupFC()}
function renderWords(){const q=(document.getElementById('historySearch').value||'').toLowerCase();const list=state.words.filter(w=>w.word.toLowerCase().includes(q));document.getElementById('wordsList').innerHTML=list.length?list.map(w=>'<article class="word-row"><div><h3>'+esc(w.word)+'</h3><div class="meta">'+esc(w.source==='daily'?'Daily Lexora':'Added by you')+' · '+new Date(w.addedAt).toLocaleDateString()+'</div><p>'+esc((w.meanings?.[0]?.definition)||'')+'</p></div><button class="audio" onclick="window.lexSpeak('+JSON.stringify(w.word)+')">🔊</button></article>').join(''):'<p>No saved words yet.</p>'}
document.getElementById('historySearch').oninput=renderWords;
function setupFC(){const words=state.words;if(!words.length){document.getElementById('fcFront').innerHTML='<span>Add words to start.</span>';document.getElementById('fcBack').classList.add('hidden');return}fcIndex=Math.min(fcIndex,words.length-1);fcFlipped=false;drawFC()}
function drawFC(){const w=state.words[fcIndex];document.getElementById('fcFront').innerHTML='<strong>'+esc(w.word)+'</strong><div>'+esc(w.phonetic||'')+'</div>';document.getElementById('fcBack').innerHTML=(w.meanings||[]).map(m=>'<p><b>'+esc(m.pos||'')+'</b> '+esc(m.definition)+'</p>').join('')||'<p>No definition stored.</p>';document.getElementById('fcBack').classList.toggle('hidden',!fcFlipped);document.getElementById('fcProgress').textContent=(fcIndex+1)+' / '+state.words.length}
document.getElementById('flashcard').onclick=()=>{fcFlipped=!fcFlipped;drawFC()};document.getElementById('fcFlip').onclick=()=>{fcFlipped=!fcFlipped;drawFC()};document.getElementById('fcStart').onclick=()=>{fcIndex=0;fcFlipped=false;setupFC()};document.getElementById('fcKnown').onclick=async()=>{if(!state.words.length)return;const w=state.words[fcIndex];w.reviews=(w.reviews||0)+1;const d=today();state.history[d]??={added:[],reviewed:[]};if(!state.history[d].reviewed.includes(w.word))state.history[d].reviewed.push(w.word);localSave();if(user){try{await cloud.from('words').update({reviews:w.reviews}).eq('id',w.id);await syncActivity()}catch(e){}}fcIndex=(fcIndex+1)%state.words.length;fcFlipped=false;drawFC();renderCalendar()};
function renderCalendar(){const cal=document.getElementById('calendar');cal.innerHTML='';const end=new Date(),start=new Date(end);start.setDate(end.getDate()-364);start.setDate(start.getDate()-((start.getDay()+6)%7));const total={};Object.entries(state.history).forEach(([d,v])=>total[d]=(v.added?.length||0)+(v.reviewed?.length||0));document.getElementById('activityTotal').textContent=Object.values(total).reduce((a,b)=>a+b,0)+' activities';for(let i=0;i<371;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=d.toISOString().slice(0,10),n=total[key]||0,c=document.createElement('div');c.className='cell '+(n>=8?'l4':n>=5?'l3':n>=3?'l2':n>=1?'l1':'l0');c.title=key+' · '+n+' activities';c.onclick=()=>{const h=state.history[key]||{added:[],reviewed:[]};document.getElementById('dayDetails').innerHTML='<b>'+d.toLocaleDateString(undefined,{weekday:'long',year:'numeric',month:'long',day:'numeric'})+'</b><br>Added: '+(h.added?.join(', ')||'None')+'<br>Reviewed: '+(h.reviewed?.join(', ')||'None')};cal.appendChild(c)}}

const modal=document.getElementById('authModal');const openAuth=()=>{modal.classList.remove('hidden');renderAuth()};const closeAuth=()=>modal.classList.add('hidden');document.getElementById('accountBtn').onclick=openAuth;document.getElementById('closeAuth').onclick=closeAuth;document.getElementById('toggleAuth').onclick=()=>{authMode=authMode==='signin'?'signup':'signin';renderAuth()};document.getElementById('signOutBtn').onclick=async()=>{if(cloud)await cloud.auth.signOut();user=null;document.getElementById('accountBtn').textContent='Sign in';toast('Signed out');closeAuth()};
function renderAuth(){const signed=!!user;document.getElementById('authTitle').textContent=signed?'Your Lexora account':(authMode==='signin'?'Sign in to Lexora':'Create your Lexora account');document.getElementById('authSubtitle').textContent=signed?user.email:'Your words will follow you to every device.';document.getElementById('authForm').classList.toggle('hidden',signed);document.getElementById('toggleAuth').classList.toggle('hidden',signed);document.getElementById('signOutBtn').classList.toggle('hidden',!signed);document.getElementById('nameWrap').classList.toggle('hidden',authMode!=='signup');document.getElementById('authSubmit').textContent=authMode==='signin'?'Sign in':'Create account';document.getElementById('authMessage').textContent=!hasCloud()&&!signed?'Cloud sync is not connected yet. Add your Supabase settings in js/supabase-config.js.':''}
document.getElementById('authForm').onsubmit=async e=>{e.preventDefault();if(!cloud){renderAuth();return}const email=document.getElementById('authEmail').value.trim(),password=document.getElementById('authPassword').value,name=document.getElementById('authName').value.trim();const btn=document.getElementById('authSubmit');btn.disabled=true;document.getElementById('authMessage').textContent='Please wait…';try{let result;if(authMode==='signin')result=await cloud.auth.signInWithPassword({email,password});else result=await cloud.auth.signUp({email,password,options:{data:{display_name:name}}});if(result.error)throw result.error;if(authMode==='signup'&&!result.data.session){document.getElementById('authMessage').textContent='Account created. Check your email to confirm it, then sign in.';return}toast('Welcome to Lexora');closeAuth()}catch(err){document.getElementById('authMessage').textContent=err.message||'Authentication failed.'}finally{btn.disabled=false}};
async function initAuth(){if(!cloud){renderAuth();return}const {data:{session}}=await cloud.auth.getSession();user=session?.user||null;updateAccount();if(user){try{await loadCloudData()}catch(e){toast('Could not load cloud data; using local data')}}cloud.auth.onAuthStateChange(async(_event,session)=>{user=session?.user||null;updateAccount();if(user){try{await loadCloudData()}catch(e){toast('Could not sync your account')}}});}
function updateAccount(){document.getElementById('accountBtn').textContent=user?(user.user_metadata?.display_name||user.email.split('@')[0]):'Sign in'}
applyTheme();renderDaily();renderWords();if(location.hash)page(location.hash.slice(1));initAuth();
})();
